package com.xzj.model;

import lombok.Data;

import java.util.Date;

@Data
public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.id
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dept_name
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dept_code
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.create_user
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.create_time
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.update_user
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    private Long updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.update_time
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.id
     *
     * @return the value of dept.id
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.id
     *
     * @param id the value for dept.id
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dept_name
     *
     * @return the value of dept.dept_name
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dept_name
     *
     * @param deptName the value for dept.dept_name
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dept_code
     *
     * @return the value of dept.dept_code
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dept_code
     *
     * @param deptCode the value for dept.dept_code
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.create_user
     *
     * @return the value of dept.create_user
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.create_user
     *
     * @param createUser the value for dept.create_user
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.create_time
     *
     * @return the value of dept.create_time
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.create_time
     *
     * @param createTime the value for dept.create_time
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.update_user
     *
     * @return the value of dept.update_user
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.update_user
     *
     * @param updateUser the value for dept.update_user
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.update_time
     *
     * @return the value of dept.update_time
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.update_time
     *
     * @param updateTime the value for dept.update_time
     *
     * @mbg.generated Wed Jul 12 15:12:49 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}