package com.xzj.model;

import lombok.Data;

@Data
public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_name
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.has_Third
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    private String hasThird;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.pid
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.order_value
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    private Integer orderValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.icon
     *
     * @return the value of menu.icon
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.icon
     *
     * @param icon the value for menu.icon
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_name
     *
     * @return the value of menu.menu_name
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_name
     *
     * @param menuName the value for menu.menu_name
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.has_Third
     *
     * @return the value of menu.has_Third
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public String getHasThird() {
        return hasThird;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.has_Third
     *
     * @param hasThird the value for menu.has_Third
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public void setHasThird(String hasThird) {
        this.hasThird = hasThird == null ? null : hasThird.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.url
     *
     * @return the value of menu.url
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.url
     *
     * @param url the value for menu.url
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.pid
     *
     * @return the value of menu.pid
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.pid
     *
     * @param pid the value for menu.pid
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.order_value
     *
     * @return the value of menu.order_value
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public Integer getOrderValue() {
        return orderValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.order_value
     *
     * @param orderValue the value for menu.order_value
     *
     * @mbg.generated Thu Jul 13 10:24:50 CST 2023
     */
    public void setOrderValue(Integer orderValue) {
        this.orderValue = orderValue;
    }
}