package com.xzj.model;

import lombok.Data;
import lombok.experimental.Accessors;

import java.util.Date;

@Data
public class Users {

    private Long id;

    private Long roleId;

    private String userName;

    private String account;

    private String password;

    private Long deptId;

    private String phone;

    private Long createUser;

    private Date createTime;

    private Long updateUser;

    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.id
     *
     * @return the value of user1.id
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.id
     *
     * @param id the value for user1.id
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.user_name
     *
     * @return the value of user1.user_name
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.user_name
     *
     * @param userName the value for user1.user_name
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.account
     *
     * @return the value of user1.account
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.account
     *
     * @param account the value for user1.account
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.password
     *
     * @return the value of user1.password
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.password
     *
     * @param password the value for user1.password
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.dept_id
     *
     * @return the value of user1.dept_id
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.dept_id
     *
     * @param deptId the value for user1.dept_id
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.phone
     *
     * @return the value of user1.phone
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.phone
     *
     * @param phone the value for user1.phone
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.create_user
     *
     * @return the value of user1.create_user
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.create_user
     *
     * @param createUser the value for user1.create_user
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.create_time
     *
     * @return the value of user1.create_time
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.create_time
     *
     * @param createTime the value for user1.create_time
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.update_user
     *
     * @return the value of user1.update_user
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.update_user
     *
     * @param updateUser the value for user1.update_user
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user1.update_time
     *
     * @return the value of user1.update_time
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user1.update_time
     *
     * @param updateTime the value for user1.update_time
     *
     * @mbg.generated Thu Jul 06 21:22:20 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}